services:
  telegram-web-hub:
    build: .
    container_name: telegram_web_hub
    restart: unless-stopped
    
    ports:
      - "3000:3000"
    
    volumes:
      - ./session_data:/app/session_data
      - ./telegram_downloads:/app/telegram_downloads
    
    environment:
      - PYTHONUNBUFFERED=1
    
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.2'
          memory: 256M
